version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devops_course
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - devopsnet

  backend:
    build: ./server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: devuser
      DB_PASSWORD: devpassword
      DB_NAME: devops_course
      # Add other env vars as needed
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - devopsnet

  frontend:
    build: ./client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - devopsnet

volumes:
  db_data:

networks:
  devopsnet:
    driver: bridge
