CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS completions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  topic VARCHAR(64) NOT NULL,
  UNIQUE KEY (user_id, topic)
);

CREATE TABLE IF NOT EXISTS user_pdfs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  path VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);